version: '3'
services:
  app:
    image: my-ml-service:latest
    build:
      context: .  # указывает на текущую директорию для сборки
      dockerfile: Dockerfile  # указывает на файл Dockerfile в этой директории
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production